/**
 * PhoneUnit domain validators.
 */

import { z } from "zod";
import {
  zBooleanString,
  zMoney,
  zNonEmptyString,
  zOptionalString,
  zPaginationQuery,
  zUuid,
} from "./shared";

// ---------------------------------------------------------------------------
// Enum mirrors from Prisma schema
// ---------------------------------------------------------------------------

export const zGrade = z.enum(["S", "A_PLUS", "A", "B", "C"]);
export type Grade = z.infer<typeof zGrade>;

export const zCondition = z.enum(["NEW", "LIKE_NEW", "GOOD", "FAIR"]);
export type Condition = z.infer<typeof zCondition>;

export const zPhoneUnitStatus = z.enum(["AVAILABLE", "SOLD", "IN_REPAIR", "DEFECTIVE", "RESERVED"]);
export type PhoneUnitStatus = z.infer<typeof zPhoneUnitStatus>;

/**
 * Statuses that can be set via the admin status-change endpoint.
 * SOLD is excluded — it can only be set via the billing transaction.
 */
export const zAdminSettableStatus = z.enum(["AVAILABLE", "IN_REPAIR", "DEFECTIVE", "RESERVED"]);
export type AdminSettableStatus = z.infer<typeof zAdminSettableStatus>;

// ---------------------------------------------------------------------------
// Create phone unit
// ---------------------------------------------------------------------------

export const zCreatePhoneUnitBody = z.object({
  /** Optional — auto-generated by the service if omitted. */
  sku: z.string().trim().max(100).optional(),
  imei: z
    .string()
    .trim()
    .regex(/^\d{14,15}$/, "IMEI must be 14 or 15 digits.")
    .optional(),
  storage: zOptionalString,
  color: zOptionalString,
  batteryHealth: z
    .number()
    .int()
    .min(0, "Battery health must be between 0 and 100.")
    .max(100, "Battery health must be between 0 and 100.")
    .optional(),
  grade: zGrade.optional(),
  condition: zCondition,
  hasBox: z.boolean().optional().default(false),
  hasCharger: z.boolean().optional().default(false),
  hasEarphones: z.boolean().optional().default(false),
  hasOriginalAccessories: z.boolean().optional().default(false),
  warrantyInfo: zOptionalString,
  sellingPrice: zMoney.optional(),
  purchasePrice: zMoney.optional(),
  adminNotes: zOptionalString,
});

export type CreatePhoneUnitBody = z.infer<typeof zCreatePhoneUnitBody>;

// ---------------------------------------------------------------------------
// Update phone unit (all optional, IMEI excluded — SUPER_ADMIN only via separate flow)
// ---------------------------------------------------------------------------

export const zUpdatePhoneUnitBody = zCreatePhoneUnitBody
  .omit({ sku: true, imei: true })
  .partial()
  .refine((v) => Object.keys(v).length > 0, {
    message: "At least one field must be provided.",
  });

export type UpdatePhoneUnitBody = z.infer<typeof zUpdatePhoneUnitBody>;

// ---------------------------------------------------------------------------
// Status change
// ---------------------------------------------------------------------------

export const zChangeUnitStatusBody = z.object({
  status: zAdminSettableStatus,
  reason: zNonEmptyString("Reason").max(500),
});

export type ChangeUnitStatusBody = z.infer<typeof zChangeUnitStatusBody>;

// ---------------------------------------------------------------------------
// Admin list units query (cross-product)
// ---------------------------------------------------------------------------

export const zListUnitsAdminQuery = zPaginationQuery.extend({
  q: z.string().trim().optional(),
  status: zPhoneUnitStatus.optional(),
  productId: zUuid.optional(),
  grade: zGrade.optional(),
  storage: z.string().trim().optional(),
  isDeleted: zBooleanString,
});

export type ListUnitsAdminQuery = z.infer<typeof zListUnitsAdminQuery>;

// ---------------------------------------------------------------------------
// List units for a specific product
// ---------------------------------------------------------------------------

export const zListProductUnitsQuery = z.object({
  status: zPhoneUnitStatus.optional(),
  grade: zGrade.optional(),
  storage: z.string().trim().optional(),
  isDeleted: zBooleanString,
});

export type ListProductUnitsQuery = z.infer<typeof zListProductUnitsQuery>;

// ---------------------------------------------------------------------------
// Path params
// ---------------------------------------------------------------------------

export const zUnitIdParam = z.object({ unitId: zUuid });
export const zProductUnitParams = z.object({ id: zUuid, unitId: zUuid });
